version: '3'

services:
  builder:
    build: .
    volumes:
      - .:/code
    command: bash -c "rm -f builds/ammo.* && cmake -B builds -DCLOSURE=1 -DCMAKE_EXPORT_COMPILE_COMMANDS=1 && cmake --build builds"
